### ISSUE TITLE
ентер в фф пляшет

### ISSUE THREAD

**Issue by recoilme** [fr4nki/oh-md#8]
пример 1
- нажать Code 
- ввести текст, нажать enter 
ожидается - внутри тега на новой строке
фактически - за границей тега - в конце строки

пример 2
плюс в конец текста прыгает по ентер в фф (это скорей всего всё один баг в фф)

пример 3
4 ентера в фф вместо двух:
- нажать список
- перейти в конец, нажать enter 
- генерит 4 ентера

**Comment by fr4nki** [comment]
Fixed at 2.1.16
